services:
  # phpService:
  #   image: tubes-1:latest
  #   volumes:
  #     - ./src/server:/var/www
  #     - ./src/public:/var/www/html
  #   ports:
  #     - 8008:80
  # phpServiceDB:
  #   image: postgres:latest
  #   restart: always
  #   volumes:
  #     - "./db:/var/lib/postgresql/data"
  #     - "./src/migration:/docker-entrypoint-initdb.d/"
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  # adminer:
  #   image: adminer:latest
  #   restart: always
  #   ports:
  #     - "8080:8080"
  # clientSPA:
  #   image: clientspa:latest
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - '../clientspa:/app'
  #     - '/app/node_modules'
  #   tty: true
  restServiceDB:
      #   image: postgres:latest
      #   restart: always
      #   volumes:
      #     - "./db:/var/lib/postgresql/data"
      #     - "./src/migration:/docker-entrypoint-initdb.d/"
      #   ports:
      #     - "5432:5432"
      #   environment:
      #     POSTGRES_USER: ${POSTGRES_USER}
      #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #     POSTGRES_DB: ${POSTGRES_DB}
