services:
  # phpService:
  #   image: tubes-1:latest
  #   volumes:
  #     - ./src/server:/var/www
  #     - ./src/public:/var/www/html
  #   ports:
  #     - 8008:80
  # phpServiceDB:
  #   image: postgres:latest
  #   restart: always
  #   volumes:
  #     - "./db:/var/lib/postgresql/data"
  #     - "./src/migration:/docker-entrypoint-initdb.d/"
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
  # clientSPA:
  #   image: clientspa:latest
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - '../clientspa:/app'
  #     - '/app/node_modules'
  #   tty: true
  # soapService:
  #   image: soapservice:latest
  #   restart: always
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - soapServiceDB
  soapServiceDB:
    image: mysql:latest
    restart: always
    volumes:
      - "../soapservice/db:/var/lib/mysql"
      - "../soapservice/schema:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_SOAP}
      MYSQL_DATABASE: ${MYSQL_DATABASE_SOAP}
  restServiceDB:
    image: postgres:latest
    restart: always
    volumes:
      - "../restservice/db:/var/lib/postgresql/data"
      - "../restservice/schema:/docker-entrypoint-initdb.d/"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER_REST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_REST}
      POSTGRES_DB: ${POSTGRES_DB_REST}
